export const SUPABASE_STORAGE_BUCKET_ITEM_IMAGES = "item-images" as const;
export const SUPABASE_STORAGE_BUCKET_THUMBNAILS = "thumbnails" as const;
export const SUPABASE_STORAGE_BUCKET_HEALTH_DOCUMENTS = "health-documents" as const;

export const SUPABASE_STORAGE_ITEM_IMAGES_PATH_PREFIX = `/${SUPABASE_STORAGE_BUCKET_ITEM_IMAGES}/` as const;
export const SUPABASE_STORAGE_THUMBNAILS_PATH_PREFIX = `/${SUPABASE_STORAGE_BUCKET_THUMBNAILS}/` as const;
export const SUPABASE_STORAGE_HEALTH_DOCUMENTS_PATH_PREFIX = `/${SUPABASE_STORAGE_BUCKET_HEALTH_DOCUMENTS}/` as const;
