-- Performance optimizations generated by nightly sweep
-- Date: 2026-02-17
-- Context: Optimizing queries on health_measurements

CREATE INDEX IF NOT EXISTS idx_health_measurements_measured_at ON health_measurements (measured_at);
