// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate Supabase configuration
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ Supabase configuration error:');
  if (!SUPABASE_URL) {
    console.error('  - VITE_SUPABASE_URL is missing from environment variables');
  }
  if (!SUPABASE_PUBLISHABLE_KEY) {
    console.error('  - VITE_SUPABASE_PUBLISHABLE_KEY is missing from environment variables');
  }
  console.error('  Please check your .env file and ensure all required variables are set.');
  console.error('  See .env.example for reference.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || '', 
  SUPABASE_PUBLISHABLE_KEY || '', 
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);