// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate Supabase configuration
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const errorMessage = '❌ Supabase configuration error:';
  const missingVars: string[] = [];
  
  if (!SUPABASE_URL) {
    missingVars.push('VITE_SUPABASE_URL');
  }
  if (!SUPABASE_PUBLISHABLE_KEY) {
    missingVars.push('VITE_SUPABASE_PUBLISHABLE_KEY');
  }
  
  console.error(errorMessage);
  console.error(`  Missing environment variables: ${missingVars.join(', ')}`);
  console.error('  Please check your .env file and ensure all required variables are set.');
  console.error('  See .env.example for reference.');
  
  // CRITICAL: Throw in BOTH development AND production to prevent silent failures
  // A missing Supabase config will cause the app to fail anyway - better to fail fast with a clear error
  // This prevents the blank white screen issue where the app appears to load but crashes silently
  throw new Error(
    `Supabase configuration incomplete. Missing: ${missingVars.join(', ')}. ` +
    'Please check your environment variables.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || '', 
  SUPABASE_PUBLISHABLE_KEY || '', 
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);